### ISSUE TITLE
Possible UX Improvements (or I'm just daft, no problem if so :smiling_face_with_tear: )

### ISSUE THREAD

**Issue by CRC-Mismatch** [littlebyteorg/appledb#129]
Hi! I'd like to first thank you guys for keeping up such a great database. I used to be a jailbreaker back when I had my iPod Touches, 3rd and 4th generations, and although it was quite easier back then to find information about jailbreaking, it was still also harder to keep up with the latest news and what iOS version was or wasn't supported - we didn't have anything that concentrated all devices, iOS versions and jailbreaking methods in one place...

With that said, I feel like I had to point out some usability questions, mainly where the previous Spreadsheet made it more intuitive.

My main issue is that I can't seem to understand the connection between Device, iOS version and Jailbreak Options. I should enumerate my bothers on a "narrative" basis to make them more clear...

- I come in from Devices > [my chosen device] - I see that there's red X's and green V's that at first made me believe were related to Jailbreak status; however, after hovering over them, I noticed they mean "not signed" and "signed", which I'm not sure at all if relating to the iOS IPSW themselves, to the commit/PR that added them in to the DB, but either way, I noticed it has nothing to do with jailbreak availability. -- IMHO it's a debatable point if the main concern should be pointing at the "jailbreaker" instead of the "casual user" (or more like "casual researcher"), but I'd guess the majority of users would be looking here explicitly after jailbreaks (like I was), and it's really unintuitive what the check-marks and X's mean at first.
- After expanding any iOS version that isn't supported, I only see "View More". - By that, I thought that the "Jailbreaks" there listed would apply to my previous specific selection, but alas, no, they are generic and only apply to that specific iOS version. I later noticed that when there's a "match", whenever I expand the iOS version, the Jailbreaks are shown. -- I'd suggest keeping the "Jailbreaks" area visible in the unsupported iOS versions' accordions, either empty, or with a "No jailbreak method available" message.

**Comment by emiyl** [comment]
My plan for appledb.dev currently is for it to be primarily a source of information for just devices and software. Its sister site ios.cfw.guide is much better suited for jailbreaking.

**Comment by CRC-Mismatch** [comment]
I'd then suggest isolating them at the very least as best as possible. I understand that there's also an SEO issue, since ios.cfw.guide is probably blacklisted on the most used search platforms, and appledb isn't, and this issue was exactly the only way I got that link...

I think that linking from appledb straight to ios.cfw.guide with "synced" info would lead to even appledb itself getting blacklisted, but on the other hand, only GitHub-savvy users would be able to find their way (and on that note, I have to thank you for pointing to it), which would probably lead to lots of issues like this one, while at the same time, the novice user would be kept out of the loop... 

I'd make a JS-only way to "show the way" to the JB site, or something else "invisible" to most search engine spiders (probably by now the already process JS), anything to the likes, where a "common user" could still be lead to the right way for what he's looking after, without directly affecting appledb's  SEO rankings.

**Comment by CRC-Mismatch** [comment]
Unfortunately for me, the specific specimen I'm looking to jailbreak is running 0.2.0 more than what would be jailbreakable for its model 🥲
