### ISSUE TITLE
Potentially incorrect board/model info for iPad Pro 12.9-inch (5th Generation)

### ISSUE THREAD

**Issue by elchicano99** [littlebyteorg/appledb#14]
Hi! The board and model information from apple db for my iPad doesn't line up with what I'm seeing elsewhere, so I was hoping you could double check it.
The information I'm getting from my device (US iPad Pro 12.9" 5th Gen cellular w/1TB SSD + 16GB RAM) is that I have Model A2379, which corresponds to [iPad Pro 12.9-inch (5th generation) Wi-Fi + Cellular with mmWave](https://appledb.dev/device/iPad13,9.html) in the db. This description is correct, however that page indicates that the Identifier should be iPad13,9 — which I believe is actually the identifier for the A2378 (1 or 2 TB WiFi variant).

Every other source I can find (including those that pull directly from my device such as Blobsaver) indicates that my Identifier is iPad13,11 with board J523xAP. In the db, 13,11/J523xAP says it's the "Mainland China" model which isn't what I own. From what I can gather, iPad13,8 and iPad13,9 should both be the WiFi-only model, with 13,8 being the 128, 256, or 512 GB storage variant, and 13,9 being the 1 or 2 TB variant with extra RAM, while models 13,10 and 13,11 are the same variants but for Cellular iPads.

**Comment by Converseallstar95** [comment]
Interesting, our db lines up with IPSW's Reincubate Lookup integration, as well as EveryMac. If you have a Mac could you plug your device into Apple Configurator or Finder and see what it shows as the A model and the device ID (iPadx,y)? If not, there are some Windows programs like iMazing that can show you device info (I don't remember if iTunes does when you click on the serial number).

**Comment by elchicano99** [comment]
I just had a look at EveryMac and can confirm that it also seems to be inaccurate. Plugging in to Configurator or Finder tells me
iPad Pro (12.9-inch) (5th generation) • 992.69 GB • Model: iPad13,11
It doesn't seem to list the A model anywhere that I could find, but on the iPad under About (and engraved on the casing) shows A2379 (and MHP13LL/A).

A similar resource to EveryMac that unfortunately is only available as a Mac or iOS app that does seem to display the info correctly (which also lines up with Apple's tech specs website) is MacTracker (https://mactracker.com/):

![FD405E3D-AC92-48FE-9375-C0EC4FBF39A4](https://user-images.githubusercontent.com/5944900/165208729-32d0fb7f-68b2-4731-a22c-4aa7de83ca44.jpeg)
![3FE3335D-B2AA-4E55-9EED-93E5360B6724](https://user-images.githubusercontent.com/5944900/165208732-314c32ed-939a-4653-85f9-e1140f0d3e58.jpeg)

**Comment by Converseallstar95** [comment]
Ok thank you, we will look into all the M1 iPads :)
