### ISSUE TITLE
Rename audioOS for 13.4+

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#171]
11.3 - 13.31 are **audioOS**
13.4 and beyond should be renamed **HomePod Software**

**Comment by ROSeaboyer** [comment]
Currently the earlier releases are displayed as iOS and are bundled in the iOS subfolder; did we want to move the HomePod references into the audioOS subfolder instead as part of this adjustment?

**Comment by aaronp613** [comment]
yeah cant hurt to have them all together. Studio Display is technically iOS but has its own category
