### ISSUE TITLE
Add accessories batteries 

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#176]
1. A1645 - magic keyboard 2 battery 
2. A1612- Apple Pencil 1 battery
3. A1672 - Magic Mouse 2 battery 
4. A1542 - Magic Trackpad 2 battery
5. A2362 - MagSafe Battery Pack Battery

**Comment by ROSeaboyer** [comment]
A1617 - iPhone 6s Smart Battery Case battery
A1770 - iPhone 7 Smart Battery Case battery
