### ISSUE TITLE
Get to the bottom of AirPods Pro 2 model numbers

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#177]
A2617
A2618
A2619
A2698
A2699
A2700
A2931

https://www.reddit.com/r/airpods/comments/ypwiua/comment/ivmxg5a/

**Comment by ROSeaboyer** [comment]
A2617-A2619 were never FCC-certified, and it appears as though those labels were for pre-production units that somehow got into iOS 16 for a period; most reports on Reddit, for example, indicate that the numbers "changed" to the proper numbers at some point.

A2698 is the right ear, A2699 is the left ear, and A2700 is the case.

A2931, however, I've seen popping up in pictures for both ears, although the ones that seem more trustworthy are for the right ear as opposed to the left. It could be that A2931 is either a different manufacturing location or fixes some sort of an issue

**Comment by aaronp613** [comment]
I think we should still add A2617-A2619 though just so we have it documented

**Comment by ROSeaboyer** [comment]
All part numbers are in AppleDB; I think this issue was just to make sure we didn't have extra numbers compared to what Apple has listed

**Comment by aaronp613** [comment]
Then what are we going to do with A2617-A2619
