### ISSUE TITLE
Add beats accessories

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#179]
b0508
<img width="1154" alt="b0508" src="https://github.com/littlebyteorg/appledb/assets/40034348/18173eff-936c-4eab-8136-18d0258af90d">

b0509 (we have 509 but it might be 508 and mislabled. figure it out
<img width="814" alt="B0509" src="https://github.com/littlebyteorg/appledb/assets/40034348/0a1a5c83-0133-4002-8b04-8a8a38203608">

B0521
![B0521](https://github.com/littlebyteorg/appledb/assets/40034348/d1064369-84ae-481b-ba78-4624375dff91)

B0523
<img width="1071" alt="B0523" src="https://github.com/littlebyteorg/appledb/assets/40034348/d4463846-d690-4f92-b44e-75f98a0a3d16">

B0525
<img width="1119" alt="B0525" src="https://github.com/littlebyteorg/appledb/assets/40034348/81541b35-2cdd-4a31-bb1c-ee1da2af94f7">

B0528
<img width="977" alt="B0528" src="https://github.com/littlebyteorg/appledb/assets/40034348/90aeb7d5-d9be-4c3e-8d36-d60184024eba">

**Comment by ROSeaboyer** [comment]
These were all added earlier, closing issue
