### ISSUE TITLE
come up with a better way at handling separate buds 

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#210]
![Screenshot 2023-08-16 at 21 51 19](https://github.com/littlebyteorg/appledb/assets/40034348/151a3556-dd65-485b-9c74-975659530818)

**Comment by ROSeaboyer** [comment]
What about having a single file for both buds and have that file contain the model number for both sides, similar to what we do today for Beats?

**Comment by aaronp613** [comment]
We used to do that but we wanted to differentiate what model is what bud. We planned on moving beats to this as well once we had a good solution

**Comment by ROSeaboyer** [comment]
Another option might be to have a "subgroup" for the set of buds, with a hierarchy of (for example) AirPods -> AirPods (3rd generation) -> AirPods (Left, 3rd generation), AirPods (Right, 3rd generation). I'm not sure if the site would properly display that, however

**Comment by aaronp613** [comment]
I think we will need to come up with a new way of handling them from both the appledb-web side and just how we format them. 

Perhaps handle it like software to some extend and have them both in one json but we list it in a special way

**Comment by emiyl** [comment]
Yeah this is an appledb-web issue which I will fix. Not an issue with appledb itself

**Comment by aaronp613** [comment]
well we may need to format the jsons properly to handle this, no?

**Comment by emiyl** [comment]
I thought the link was identical for both buds? If they are identical, it's just a case of appledb-web finding identical links within a device group and then merging.

**Comment by aaronp613** [comment]
Yes links are identical. I guess we will see how you implement it and go from there.

The other issue will be how we handle beats. Since there are a shit ton of special edition ones
