### ISSUE TITLE
Add Def1nit3lyN0tAJa1lbr3akTool

### ISSUE THREAD

**Issue by gamer191** [littlebyteorg/appledb#250]

**Comment by jthoward64** [comment]
I've been using it, relatively stable but still somewhat incomplete (no restore RootFS, no userspace reboot, and SSH is sorta broken)

**Comment by TheMasterOfMike** [comment]
> I've been using it, relatively stable but still somewhat incomplete (no restore RootFS, no userspace reboot, and SSH is sorta broken)

Jailbreak removal functionality is definitely something that's missing, but it's not essential either (palera1n and erasing all content and settings both exist). Userspace Rebooting isn't much of a missing feature considering that ldrestart exists which - while worse - should serve most of the needs that a userspace reboot would.

As for SSH, I'd have to take a look at that, but that's also not something that matters for most end users.
