### ISSUE TITLE
XinaA15 & Dopamine should not be listed as jailbreaks.

### ISSUE THREAD

**Issue by refriedfood** [littlebyteorg/appledb#257]
They are rootless tweaks that leave the file system read-only, and a marker or some sort of delineation should be noted on the website for such. The definition of jailbreaking is to make a read-only file system writable by the user. Neither of these qualify.

**Comment by dashboarde** [comment]
Do you want bootloop day 1? Do you want all apps to easily detect jailbreak? That’s the whole point of rootless.
- Preventing system file modification makes it a lot safer to use, what if you accidentally delete `/sbin/launchd` or `/usr/lib/dyld`? Boom. Restore to latest.
- What if you wanna use bank apps? Rootless (and also another variant, RootHide) makes it a lot more difficult to detect jailbreak.
