### ISSUE TITLE
watchOS 8.7.1 needs an iPSW

### ISSUE THREAD

**Issue by aaronp613** [littlebyteorg/appledb#75]

**Comment by nicolas17** [comment]
I'll probably get access to this soon™.

**Comment by truonggiang0710** [comment]
@nicolas17 @aaronp613 
Is it available now?

**Comment by aaronp613** [comment]
As of this morning, no

**Comment by truonggiang0710** [comment]
@nicolas17 @aaronp613  any update, please?

**Comment by truonggiang0710** [comment]
> I'll probably get access to this soon™.

After 7 days, nothing is updated.

**Comment by truonggiang0710** [comment]
@aaronp613 @nicolas17 Do you have any update?

**Comment by aaronp613** [comment]
@truonggiang0710 When we have one we will post it. Stop asking.
