### ISSUE TITLE
Links from specific firmware version back to device are broken

### ISSUE THREAD

**Issue by mbirth** [littlebyteorg/appledb#99]
E.g. if I am on https://appledb.dev/firmware/Apple-Watch-Magnetic-Charging-Cable-Firmware/10M1279 and click on the device name, the link points to:

    https://appledb.dev/device/identifier/Apple%20Watch%20Magnetic%20Fast%20Charger%20to%20USB-C%20Cable

which returns a 404 error because the correct URL is:

    https://appledb.dev/device/identifier/Apple-Watch-Magnetic-Fast-Charger-to-USB-C-Cable

**Comment by aaronp613** [comment]
@emiyl

**Comment by emiyl** [comment]
this is an issue with https://github.com/littlebyteorg/appledb-web, and has been fixed in 0fa3398
